### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Jonztu**

### CODE REVIEW

**Comment by NitroXenon** [comment]
Thanks for the PR! May I have your name which will be displayed in the translation credit page? Thanks a lot xD

**Comment by Jonztu** [comment]
My name is Jonne Tuomivaara. Happy to contribute.

**Comment by NitroXenon** [comment]
@Jonztu Is the strings.xml file saved as UTF-8 encoding? I got many ```�``` (question mark in rhombus sign) when I view this file as raw.

**Comment by NitroXenon** [comment]
Maybe I'm afraid that I can't add Finnish translation right now.

**Pull request merged**
