### PR TITLE
Some more minor fixes

### PR DESCRIPTION
**Pull request by xmat123x**
-Standardized upper and lower case letter use for the categories
-Shrunk uneccessarily long sentences to make them fit better on portrait
oriented devices
-Fixed a handful of grammatical errors

### CODE REVIEW

**Comment by NitroXenon** [comment]
Please add this string so I can merge it without conflict. Thanks bro.

https://github.com/NitroXenon/TerrariumTV-Localization/blob/master/values/strings.xml#L191

**Comment by xmat123x** [comment]
Should I close this pull request and submit an other one with the string added?

**Comment by NitroXenon** [comment]
You can add commit to this PR.

**Comment by NitroXenon** [comment]
Oh it still has conflict. You have to close this and open a new one.

**Pull request closed without merging**
